---
- hosts: [ "node"]
  user: vagrant
  become: yes
  tasks:

  - include: tasks/dependencies.yml
  - include: tasks/repositories.yml
  - include: tasks/java-install.yml
  - include: tasks/dse-install.yml
  - include: tasks/start-dse.yml
  - include: tasks/copy-data.yml
